# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_app_then_launch:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    name: Launch Broken Crystals
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt update
          sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo apt-get install nodejs-dev node-gyp libssl1.0-dev
          sudo apt-get install nodejs npm
      - name: Docker-Compose
        run: |
          sudo docker-compose up -d
          sudo docker-compose config
      - run: sleep 30s
  
      - name: OWASP ZAP FULL Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: 'http://brokencrystals.local'    # http://localhost:8000'
          fail_action: 'false'
          token: ${{ secrets.GITHUB_TOKEN }}
  
  
